typography_spectrum: 0.4451613596174866
color:
  brandStrength: 0.29573256173171103
  lightness: 0.22910023224540055
  saturation: 0.6724965134635568
  rhythmicContrast: 0.9739110507071018
  brandColors:
    - '#FFF8E3'
    - '#CCCC9F'
    - '#33332D'
    - '#9FB4CC'
    - '#DB4105'
layout_spectrum: 0.06419099750928581
author:
  name: Joe Cole
  email: joe.unlimited@hotmail.com
name: Joe Cole - English Teacher
navigation:
  - name: About Me
    id: 838c303a-6ed4-44c6-8323-96e3785edb69
    type: content
  - name: LinkedIn
    url: >-
      http://www.linkedin.com/in/joe-cole-6810b7b9?trk=nav_responsive_tab_profile
    type: external
  - name: Contact Me
    url: 'http://www.123contactform.com/form-2113579/Contact-Lead-Form'
    type: external
title: ''
description: ESL is on a Mission
