typography_spectrum: 0.28299630363471806
color:
  brandStrength: 0.40609478624537587
  lightness: 0.6876867061946541
  saturation: 0.038105882704257965
  rhythmicContrast: 0.15376864094287157
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
layout_spectrum: 0.06419099750928581
author:
  name: Joe Cole
  email: joe.unlimited@hotmail.com
name: Joe Cole - English Teacher
navigation: []
title: ESL is on a Mission
description: ESL is on a Mission
