layout_spectrum: 0.5923620932735503
typography_spectrum: 0.49017470655962825
color:
  brandStrength: 0.9638162171468139
  lightness: 0.6380815515294671
  saturation: 0.7895422514993697
  rhythmicContrast: 0.5010115541517735
  brandColors:
    - '#FFFFFF'
    - '#F39801'
    - '#5A5655'
    - '#14AE66'
    - '#C10E23'
author:
  name: Joe Cole
  email: joe.unlimited@hotmail.com
name: Joe Cole - English Teacher
navigation:
  - name: About
    id: 838c303a-6ed4-44c6-8323-96e3785edb69
    type: content
  - name: LinkedIn
    url: >-
      http://www.linkedin.com/in/joe-cole-6810b7b9?trk=nav_responsive_tab_profile
    type: external
  - name: Contact
    url: 'http://www.123contactform.com/form-2113579/Contact-Lead-Form'
    type: external
title: ''
description: ESL is on a Mission
